name: delivery_micros_services
description: Aplicativo de venda consumindo um micro serviço.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.3
  hexcolor: 2.0.5
  font_awesome_flutter: 10.1.0
  otp_text_field: 1.1.3
  flutter_secure_storage: 4.2.1
  cached_network_image: 3.1.0
  localstorage: 4.0.0+1
  badges: 2.0.3
  intl: 0.17.0
  http: 0.13.3
  provider: 6.0.1
  equatable: 2.0.3
  get: 4.3.8
  qr_flutter: 4.0.0
  add_to_cart_animation: 0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.9.2
  test: 1.17.10
  mocktail: 0.1.4
  faker: 2.0.0
  network_image_mock: 2.1.1

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/icon/android.png
  image_path_ios: lib/ui/assets/icon/ios.png
  adaptive_icon_background: lib/ui/assets/icon/background.png
  adaptive_icon_foreground: lib/ui/assets/icon/foreground.png